---
services:
  spack-registry:
    image: registry:3.1.1
    container_name: spack-oci-registry
    restart: unless-stopped

    ports:
      - "5000:5000"

    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry

    volumes:
      - ${SPACK_REGISTRY_DATA:-/srv/spack/oci-registry}:/var/lib/registry
...
